---

- name: create group for borg
  group:
    name: "{{ borgbackup_server_group }}"
    state: present

- name: create user for borg
  user:
    name: "{{ borgbackup_server_user }}"
    group: "{{ borgbackup_server_group }}"
    home: "{{ borgbackup_server_home }}"
    createhome: yes
    state: present

- name: manage permissions
  file:
    path: "{{ item }}"
    owner: "{{ borgbackup_server_user }}"
    group: "{{ borgbackup_server_group }}"
    mode: 0700
    state: directory
  with_items:
    - "{{ borgbackup_server_home }}"
    - "{{ borgbackup_server_home }}/.ssh"
    - "{{ borgbackup_server_pool }}"

- name: manage permissions for authorized_keys
  file:
    path: "{{ borgbackup_server_home }}/.ssh/authorized_keys"
    owner: "{{ borgbackup_server_user }}"
    group: "{{ borgbackup_server_group }}"
    mode: 0600
    state: touch

- name: deploy prune scripts
  template:
    dest: "{{ borgbackup_server_scripts_dir }}/{{ item.name }}.sh"
    src: prune_job.sh.j2
    owner: root
    group: root
    mode: 0700
  with_items: "{{ borgbackup_prune_jobs }}"

- name: schedule prune scripts on cron
  cron:
    name: "borg prune {{ item.name }}"
    user: root
    job: "{{ borgbackup_server_scripts_dir }}/{{ item.name }}.sh"
    day: "{{ item.day | default('*') }}"
    hour: "{{ item.hour | default('1') }}"
    minute: "{{ item.minute | default('0') }}"
    state: present
  with_items: "{{ borgbackup_client_jobs }}"
