---

- name: generate backup ssh-key
  user:
    name: root
    ssh_key_file: "{{ borgbackup_client_ssh_key_file }}"
    ssh_key_bits: 4096
    generate_ssh_key: yes

- name: fetch backup ssh-pubkey
  command: "cat {{ borgbackup_client_ssh_key_file }}.pub"
  always_run: yes
  register: borgbackup_client_ssh_pubkey_file
  changed_when: False

- name: add ssh-pubkey to backup server
  delegate_to: "{{ borgbackup_client_backup_server }}"
  authorized_key:
    user: "{{ borgbackup_server_user }}"
    key: "{{ borgbackup_client_ssh_pubkey_file.stdout }}"
    key_options: 'command="cd {{ borgbackup_server_pool }}/{{ inventory_hostname }};borg serve --restrict-to-path {{ borgbackup_server_pool }}/{{ inventory_hostname }}",no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-user-rc'

- name: create repo path for host
  delegate_to: "{{ borgbackup_client_backup_server }}"
  file:
    path: "{{ borgbackup_server_pool }}/{{ inventory_hostname }}"
    owner: "{{ borgbackup_server_user }}"
    group: "{{ borgbackup_server_group }}"
    mode: 0700
    state: directory

- name: backup scripts dir
  file:
    path: "{{ borgbackup_client_scripts_dir }}"
    owner: root
    group: root
    mode: 0750
    state: directory

# TODO: the failed_when is not optimal and the task might need to run twice under certain circumstances
- name: initialize repositories
  command: "/usr/bin/borg init --encryption none {{ borgbackup_server_user }}@{{ borgbackup_client_backup_server }}:{{ item.name }}"
  environment:
    - BORG_RSH: "ssh -o StrictHostKeyChecking=no -i {{ borgbackup_client_ssh_key_file }}"
  with_items: "{{ borgbackup_client_jobs }}"
  register: borgbackup_initialize_result
  failed_when: (borgbackup_initialize_result.stderr != "") and ('already exists' not in borgbackup_initialize_result.stderr)

- name: backup scripts
  template:
    dest: "{{ borgbackup_client_scripts_dir }}/{{ item.name }}.sh"
    src: job.sh.j2
    owner: root
    group: root
    mode: 0700
  with_items: "{{ borgbackup_client_jobs }}"

- name: backup cronjobs
  cron:
    name: "borg backup {{ item.name }}"
    user: root
    job: "{{ borgbackup_client_scripts_dir }}/{{ item.name }}.sh"
    day: "{{ item.day | default('*') }}"
    hour: "{{ item.hour | default('1') }}"
    minute: "{{ item.minute | default('0') }}"
    state: present
  with_items: "{{ borgbackup_client_jobs }}"
